export const KULLANICI_SOZLESMESI = `
KULLANICI SÖZLEŞMESİ, KULLANIM KOŞULLARI ve İADE KOŞULLARI

Taraflar
İşbu Akademik Masa Online Kullanıcı Sözleşmesi ve Kullanım Koşulları (kısaca “Sözleşme”) www.akademikmasa.com uzantılı web sitesinin, aplikasyonunun ve buna bağlı tüm uygulamaların (kısaca “Site”) tüm haklarının sahibi olan Akademik Masa ile kimlik ve iletişim bilgilerini işbu Sözleşme’nin kabulü öncesinde sisteme tanımlamış olan veya tanımlamamış olsa dahi Site’den hizmet satın alan Kullanıcı arasındadır.
Sözleşme’nin Konusu
İşbu Sözleşme’nin konusu Akademik Masa’nın sahibi olduğu platform üzerinden hizmet satın alma imkanının sağlanması ve tarafların karşılıklı hak ve yükümlülüklerinin belirlenmesidir. Kullanıcının, Site’den alışveriş yapması halinde, işbu Sözleşme’nin tamamını okuduğunu, anladığını ve tüm hükümlerini onayladığını kabul, beyan ve taahhüt eder.
Akademik Masa’nın Hakları
Akademik Masa güvenlik nedeniyle Müşteri’nin Site üzerindeki her türlü aktivitesini izleyebilir, kayda alabilir ve/veya gerekli gördüğünde, Site'den uzaklaştırma, Kullanıcı dondurma, Kullanıcı iptal etme ve benzeri her türlü müdahalede bulunabilir.
Akademik Masa önceden Kullanıcı’ya bildirimde bulunmaksızın Site'nin biçim ve içeriğini kısmen ve/veya tamamen değiştirebileceği gibi, Site'nin yayın yaptığı alan adını değiştirebilir, farklı alt alan adları kullanabilir, alan adı yönlendirmesi yapabilir ve/veya alan adını kapatabilir.
Akademik Masa Sözleşme’de belirtilen iş ve/veya işlemlerin daha etkin gerçekleştirilebilmesi açısından dilediği zaman hizmet, satış şartları ve/veya işleyişte değişiklikler ve/veya güncellemeler yapabilir. Kullanıcılar işbu değişiklikleri kabul ettiklerini, bu değişikliklere uygun davranacaklarını şimdiden kabul ve beyan ederler.
Akademik Masa 6698 sayılı Kanun hükümleri uyarınca aydınlatma yükümlülüğü ve gerekmesi halinde rıza alma yükümlüklerini yerine getirmek ve sair güvenlik önlemlerine uymak şartıyla kullanıcı profili ve pazar araştırmaları yapmak, satış ve site kullanım istatistikleri oluşturmak gibi amaçlar dahil ancak bunlarla sınırlı olmamak üzere tüm yasal amaçlar için, Kullanıcı'nın kimlik, adres, iletişim ve site kullanım bilgilerini bir veri tabanında toplayabilir ve bu bilgileri işleyebilir. Ayrıca Akademik Masa bu bilgileri, yasaların getirdiği zorunluluklara uyma amacıyla veya yetkili adli veya idari otoritenin yürüttüğü soruşturma veya araştırma açısından talep edilmesi durumunda veya kullanıcıların hak ve güvenliklerinin korunması amacıyla üçüncü kişi/kurumlarla paylaşabilir.
Akademik Masa sisteminde satışa sunulan ürünlerin ve hizmetlerin fiyat ve ürün özellik bilgilerini değiştirme yükümlülüğü Akademik Masa ‘ya aittir.
Akademik Masa, ileride doğacak teknik zaruretler ve mevzuata uyum amacıyla kullanıcıların aleyhine olmamak kaydıyla işbu Sözleşme’nin uygulamasında değişiklikler yapabilir, mevcut maddelerini değiştirebilir veya yeni maddeler ilave edebilir.
Kullanıcı tarafından veya sadece referans kolaylığı nedeniyle Akademik Masa tarafından link verilmiş ise bu  Akademik Masa’nın verilen linklerin yöneldiği internet sitelerini desteklemek amacıyla verilmiş olduğu anlamında yorumlanamaz veya Akademik Masa tarafından söz konusu internet sitesi veya içeriğine yönelik herhangi bir beyan veya garanti verildiği şeklinde kabul edilemez. Bu şekilde erişilen siteler, dosyalar ve içerikler ile ilgili Akademik Masa hiçbir sorumluluk kabul etmez. 
Müşteri’nin Yükümlülükleri
Kullanıcı hizmet almak olmak isterse, Site’de belirtilen satın alma prosedürünü yerine getirerek satın alma işlemini yapması ile tamamlanır. Kullanıcı, hizmeti satın almakla birlikte, işbu Sözleşme hükümlerini, üyeliğe ve hizmetlere ilişkin Akademik Masa tarafından açıklanan/açıklanacak her türlü beyanı da kabul etmiş olmaktadır.
Kullanıcı, işlemlerinde belirtmiş olduğu kimlik, ödeme bilgileri, adres ve/veya iletişim bilgilerinin eksiksiz ve doğru olduğunu, bilgilerinde değişiklik olması halinde bu bilgileri derhal yazılı olarak Akademik Masa’ya ileteceğini, eksik, güncel olmayan ve/veya yanlış bilgi vermesi nedeniyle ortaya çıkabilecek her türlü hukuki uyuşmazlık ve/veya zarardan sadece kendisinin sorumlu olacağını kabul ve beyan eder. Akademik Masa ’ya bu nedenle hiçbir sorumluluk izafe edilemez.
Kullanıcı, Site’de belirtilen hizmetlerden faydalanırken T.C. yasalarına ve genel ahlak kurallarına uygun hareket edeceğini, hakaret, tehdit, iftira, taciz ve benzeri eylemlerde bulunmayacağını, siyasi ve/veya ideolojik propaganda yapmayacağını, diğer Müşteri'leri rahatsız edici davranışlar içine girmeyeceğini, kişi ve/veya kurumları lekeleyici her türlü davranıştan uzak duracağını ve Site'de verilen hizmetlerin aksamasına ya da kesilmesine neden olabilecek her türlü hareketten kaçınacağını, aksi halde oluşacak her türlü zarardan bizzat sorumlu olacağını kabul ve taahhüt eder.
Kullanıcı, üçüncü şahısların fikri mülkiyet hukuku kapsamındaki haklarını ihlal etmeyeceğini, üçüncü kişilerin telif haklarına saygılı olacağını, haksız rekabette bulunmayacağını ve üçüncü şahısların ticari sırlarına ve özel hayatlarına saygılı olacağını kabul ve taahhüt eder.
Kullanıcı, Site'yi kullanırken, kullanıcı adı, şifre ve benzeri bilgilerini başkalarıyla paylaşmayacağını ve bu güvenliğinden bizzat ve sadece kendisinin sorumlu olacağını, hiçbir şekilde Akademik Masa’nın sorumlu olmayacağını kabul ve beyan eder.
Kullanıcı, hileli davranışlarda bulunmayacağını, Site'nin güvenlik mekanizmasına müdahale etmeyeceğini aksi halde oluşabilecek her türlü zarardan sorumlu olduğunu ve Akademik Masa’nın uğrayacağı tüm zararları karşılayacağını taahhüt eder.
Kullanıcı’nın, bilgisayar donanımını etkileyen virüs saldırılarından ve/veya Site’den edindiği bilgiler sebebiyle veya Site’ye erişimine ve kullanımına ilişkin olarak doğrudan veya dolaylı olarak meydana gelebilecek zararlardan Akademik Masa sorumlu değildir.



Tanıtım ve Pazarlama Faaliyetlerine İlişkin İzinler
Kullanıcı, kayıt işlemleri esnasında veya sınav sonrasında kendi rızasıyla beyan ettiği sınav sonucu, başarı sırası, puanı, ad-soyad, profil fotoğrafı ve kuruma ilettiği memnuniyet mesajlarının; Hizmet Sağlayıcı (Kurum) tarafından sosyal medya mecralarında, web sitesinde, dijital reklam ve tanıtım materyallerinde yayınlanmasını kabul ve beyan eder.
İşbu izin hiçbir şekilde mesafeli satış sözleşmesinin ifası veya hizmetin sunulması için bir ön şart değildir. Alıcı, verdiği açık rızayı dilediği zaman [destek/iletişim e-posta adresi] üzerinden bildirimde bulunarak geri alma hakkına sahiptir. Rızanın geri alınması, bu tarihe kadar gerçekleşmiş olan tanıtım ve paylaşımların hukuka uygunluğunu etkilemez.


İPTAL İADE KOŞULLARI
​
Hizmet İade Koşulları
​
Satın aldığınız Canlı/Online Ders paketleri, Satın alma gerçekleştiği andan ibaren 14 gün içinde akademikmasa@gmail.com   adresine dilekçe ile başvuruda bulunarak aşağıdaki koşullar dahilinde iptal- iade/cayma hakkınızı kullanabilirsiniz.
Paket Bedelinin %10’u + (Paket/Ürün Bedeli / Toplam Ders Saati) * İşlenilen Ders Saati kadar ücret + ders takip notları bedeli için iade yada iptal işlemi yapılamaz. Kalan tutarın iade ya da iptali yapılarak belirtilen hesaba aktarılır.
Ayrıca; İptal etmek istediğiniz sırada henüz Canlı eğiminiz başlamamış ise sadece hediye edilen video ders ücreti(önceki yıl video dersleri) talep edilir. Ayrıca bir kesinti yapılmaz.

Aldığınız Eğitim sadece bir Video Ders paketi ise;
“6502 sayılı Kanun ve 29188 sayılı Resmi Gazete’de yayımlanarak yürürlüğe giren Mesafeli Sözleşmeler Yönetmeliği md. 15 kapsamında “Elektronik ortamda anında ifa edilen hizmetler veya tükeciye anında teslim edilen gayrimaddi mallara ilişkin sözleşmeler”den olup, üyelik hesabının açıldığına dair bilgilendirme yazısının HİZMET ALAN’a elektronik posta yoluyla gönderimi ile HİZMET ALAN’ın cayma hakkı ortadan kalkmış olmaktadır. HİZMET ALAN, kendisine gönderilen e-postayı almadığını, e-postayı açmadığını, hesabı kullanmadığını v.b. iddia etmek sureyle cayma beyanında bulunsa dahi, bilgilendirme metnini ihva eden e-postanın SATICI’nın e-posta sunucusundan çıkmış olması sebebiyle sözleşme konusu ürün, HİZMET ALAN’a teslim edilmiş sayılır.” hükmü gereğince iade yapılmamaktadır.
NOT: Kampanyalı dönemde kayıt olunan eğitim programlarında ve KAMP Programlarımızda iade süreci bulunmamaktadır.
Herhangi bir paket iptal ettirdiğiniz takdirde eski öğrenci statünüz düşer ve eski öğrencilerimizin yararlandığı indirimlerden ve kampanyalardan yaralanamazsınız.
`;

export const GIZLILIK_SOZLESMESI = `
Gizlilik Kuralları, Site Kullanım Şartları ve İletişimler ile Kişisel Verilerinize İlişkin Bilgilendirme
​
Değerli Site Ziyaretçilerimiz, Müşterilerimiz, Üyelerimiz,
Gizlilik Kurallarımız, İletişimler, Site Kullanım Şartları ve Kişisel Verilerinizin İşlenmesi ile ilgili uygulamalarımız ve Kisisel Verilerin Korunması Kanunu kapsamındaki haklarınız hususunda sizleri bilgilendirmek isteriz.
Şirketimiz Akademik Masa, ziyaretçi-üye-müşteri (bundan böyle kısaca Ziyaretçi(ler) diye anılacaktır) bilgilerinin gizliliği, kişisel verilerin (bilgilerin) korunması, saklanması, işlenmesi-kullanımı-imhası, ticari elektronik iletişimler ve diğer hususlarda, aşağıda cari esasları belirtilen Gizlilik Kuralları-Politikası ve Uygulama-Kullanım Şartları geçerlidir.
Bilgilerin Korunması
Ziyaretçiler tarafından verilen ve taraflarından edinilen bilgilerin ve işlemlerinin güvenliği için gerekli önlemler bilgi ve işlemin mahiyetine göre Şirketimiz veya ilgili kuruluşca sistemlerde ve internet altyapısında, teknolojik imkanlar ve maliyet unsurları dahilinde, uygun teknik ve idari yöntemler ile alınmıştır.
Sitemizi kullanımlarınızda (varsa) tüm kredi kartı işlemleri ve onayları Şirketimiz’den bağımsız olarak ilgili Banka veya Kart Kuruluşlarınca online olarak aranızda gerçekleştirilmekte olup Kredi kartı “şifresi” gibi bilgiler Şirketimiz tarafından görülmez ve kaydedilmez.
Sitemize üyelik, (varsa) ürün/hizmet satın alma ve bilgi güncelleme amaçlı girilen bilgiler, keza kredi kartı ve banka kartlarına ait gizli bilgiler, diğer internet kullanıcıları tarafından görüntülenemez.
Bilgilerin Toplama Yöntemleri, İşlenme-Aktarım Amacı ve Kişisel Veri İşlemleri
Gizliliklerinin korunması için gereken tedbirler alınmak ve kişisel verilerin işlenmesine dair tüm yasal ilkeler ile kişisel veri saklama-imha politikalarına uygun olmak üzere;, kanunen zorunlu ise bazı uygulamalar için ayrıca izni de rica edilerek; Ziyaretçilerimizin fiziki ve sanal işletmeleri ziyaret, alışveriş ve iletişim bilgileri ile aşağıda detaylı belirtilen diğer kişisel bilgileri,
Veri Sorumlusu Şirketimiz Akademik Masa ve keza Şirketiniz-anılanların ortakları-iş ortakları, halefleri, servis sağlayıcıları-tedarikçileri ve belirlenecek (sosyal medya-online reklam işletmecileri dahil) diğer işlenme amacının gerektirdiği üçüncü kişiler/kuruluşlar (duruma göre veri sorumluları, işleyenler ve/veya alıcı grupları) tarafından ve arasında,
gerek aldıkları veya ilgilendikleri ürün-hizmetler ile ilgili müşteri deneyimleri, tüketici hakları, müşteri/üye hizmetleri ve bunlara ilişkin ticari-mali ve hukuki sorumluluk-yükümlülüklerin gerçekleştirilmesine dair yasal nedenlerle, gerek genel ve kişiye özel ürün-hizmet ve imkanlardan yararlandırılabilmeleri için ve gerek ise her türlü ürün-hizmet tanıtımı, reklam, iletişim, promosyon, satış, pazarlama, mağaza kartı, kredi kartı ve kullanıcı/üyelik/müşteri bilgilendirmeleri, işlemleri ve uygulamaları yapılması amacıyla,
böylece burada belirtilen ve ayrıca kanunlarda kişisel verilerin işlenebileceği ve aktarılabileceği açıkça öngörülen hallerde, bilgilerin tarafınca alenileştirildiği durumlarda, her türlü tüketici, üyelik ve diğer sözleşmelerin kurulması veya ifasıyla doğrudan doğruya ilgili olarak sözleşme taraflarına ait kişisel verilerin işlenmesinin gerekli olduğu hallerde, keza veri sorumlusu/işleyen olarak her türlü hukuki yükümlülükleri yerine getirebilme için zorunlu durumlarda, ayrıca hakların tesisi, kullanılması veya korunması için veri işlemenin ve aktarmanın zorunlu olduğu durumlar ile temel hak ve özgürlüklerine zarar vermemek kaydıyla veri sorumlusu/işleyen olarak burada ve yasalarda öngörülmüş meşru menfaatler için veri işlemenin ve aktarmanın zorunlu/gerekli olduğu hallerde,
kısmen veya tamamen otomatik olan/olmayan toplama yöntemleri ile (Ziyaretçilerin Şirketimize ve yukarıda anılan kuruluşlara sözlü/yazılı verdikleri bilgilerden, mağazaları ve/veya bulundukları fiziki-sanal ortamları, mobil uygulamaları dahil olmak üzere internet sitelerini ziyaretlerinden ve içerik incelemelerinden, sosyal medya ve reklam ağı işletmecilerine ait sitelerdeki üyelik ve işlem bilgilerinden, Şirketimiz ve yukarıda anılan kuruluşlar nezdindeki (fiziki ve sanal/digital) üye/kullanıcı ve çağrı merkezi işlemleri ile alışverişlere ve müşteri memnuniyetine dair ödeme-tahsilat-teslimat-şikayet-kampanya-anket işlemleri ve bunların yasal mali belgeleri ile diğer belgeleri-kayıtlarından, ayrıca sabit-mobil nitelikli internet ve iletişim cihazlarının ve/veya mobil uygulamaların muhtelif ortamlarda ve yerde kullanımlarında oluşan/edinilen yazılı, sözlü, görsel ve teknik verilerden) temin, devralınma, yasal azami süreler aşılmamak üzere ve bilginin mahiyetine göre işlenme amacına uygun olarak öngörülecek süre ile yurt tercihleri, beğenileri ve ilgili yorumları, yararlanılan/katılınan kampanya, yarışma, anket vb.leri ile içerikleri, fatura içerikleri, ödeme yöntemleri, şifre gibi gizli bilgiler hariç kart ve hesap bilgileri, eski ve yeni cep/ev/iş telefon/faks numaraları, mail adresleri, elektronik ticari ve sair iletişimlere yaklaşım-aksiyonlar, çeşitli amaçlarla kullanılan sabit ve mobil cihaz ad(lar)ı, türü, modeli ve kodları, tanımlama bilgileri (çerez, web tarayıcı işaretleri-bilgisi, IP, beacon, kablolu-kablosuz ağ bağlantı bilgisi vb), reklam tanıtıcısı bilgileri, sosyal medya profil ve hesap bilgileri-işlemleri ile konum verilerinizden oluşan kişisel bilgilerinizin toplanma yöntemi ve hukuki sebebi, hangi amaçla işleneceği ve kimlere hangi amaçla aktarılabileceği hususlarında tarafınıza böylece bilgi verilmesinin yanısıra;
kişisel bilgilerinizin işlenip işlenmediğini, işlenmişse buna ilişkin bilgileri, amacına uygun kullanılıp kullanılmadığını, yurt içinde ve dışında aktarıldığı üçüncü kişileri öğrenme, bilme ve tüm bu hususlarda bilgi talep etme haklarına, keza eksik veya yanlış işlenmiş olmaları halinde düzeltilmesini, kanuni şartlarına ve yöntemine uygun olarak silinmesini veya yok edilmesini ve bu durumun verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, ayrıca, bilgilerinizin otomatik sistemler ile analiz edilmesi sureti ile aleyhinize bir sonucun ortaya çıkmasına itiraz etme ve kanuna aykırı olarak işlenmesi sebebi ile zarara uğramanız halinde giderilmesini talep etme haklarına sahip olduğunuzu,
tüm bu konularda Veri Sorumlusu Akademik Masa ‘ya başvurabileceğinizi bilgilerinize sunarız.
Yukarıdaki hususlar kişisel verilere ilişkin aydınlatma yükümlülüğümüz gereği bilgilerinize sunulmakla beraber, mevzuatın ilgili kişiden açık rıza alınmaksızın işlenmesine (aktarımlar dahil) imkan verdiği haller dışındaki her türlü kişisel veri işlemleri için izin alındığını ve izinsiz işlenme yapılmadığını bilmenizi rica ederiz.
Şirketimiz ilgili mevzuat uyarınca ve kişisel veri saklama-imha politikalarında öngöreceği periyotlarda kişisel bilgileri kısmen/tamamen imha (silme, yok etme veya anonimleştirme) işlemleri yapabileceği gibi Ziyaretçiler arzu ettikleri her zaman ve hiçbir gerekçe göstermeksizin aşağıda belirtilen iletişim kanallarından Şirketimize ulaşarak ve gereken kanuni-teknik prosedürleri yerine getirerek kişisel veri işlenmelerini ve/veya taraflarına ticari elektronik iletişimleri durdurabilirler. Bu husustaki açık bildirim-taleplerine göre, kişisel veri işlemleri ve/veya belirttiği kanallar için tarafına iletişimler yasal azami süre içinde durdurulur (yasalara göre mümkün-gereken veya yükümlü olunan kişisel veri işlemeleri ve iletişimler devam eder). Ziyaretçi dilerse ayrıca, hukuken muhafazası gereken ve/veya mümkün olanlar haricindeki bilgileri, veri kayıt sisteminden silinir ya da yok edilir veya aynı amacı sağlamak üzere kimliği belirli olmayacak biçimde anonim hale getirilir. Bu hususlardaki başvuru ve talepler yasal azami süreler içinde yerine getirilecek yahut hukuki gerekçesi tarafına açıklanarak kabul edilmeyebilecektir (İlgili kanuni haklar saklıdır).
(Bilgisayar ve diğer cihazlarınızdaki çerezler ve bildirimlere ilişkin bilgilendirmeler, bunları düzenlemek için yapabileceğiniz işlemler yukarıda belirtilmiştir).
Üçüncü Kişilere Ait Siteler-Digital Platformlar ve Uygulamalar
Sitemizden (mobil versiyonları dahil) ulaşılan diğer sitelerde kendilerine ait gizlilik-güvenlik politikaları, kullanım, iletişim ve kişisel veri işlenme şartları geçerlidir; reklam, banner, içerik görmek veya başka herhangi bir amaç ile ulaşılan web sitelerinden bilgi kullanımları, keza sitelerin (ve sair digital platformların) etik ilkeleri, gizlilik-güvenlik prensipleri, kişisel veri saklama ve imha politikaları, servis kalitesi, kullanım şartları, çerezleri-web işaretçileri ve benzerleri, bildirimleri-önerileri ve diğer uygulamaları sebebi ile oluşabilecek ihtilaf, maddi-manevi zarar ve kayıplardan Şirketimiz sorumlu değildir.
Sorumluluk
Ziyaretçilerin Sitemizden veya Sitemizde link verilen diğer sitelerden / mobil uygulamalardan / her türlü bildirimlerden ve Şirketimize ait diğer birim-mecralardan edindikleri bilgiler, taraflarına elektronik iletişimi içinde ve dışında yazılı/manyetik arşivlere kaydedilme, depolanma, saklanma, muhafaza, elde edilebilir hale getirilme, kullanılma, güncellenme, değiştirilme, birleştirilme, yeniden düzenlenme, sınıflandırılma, açıklanma, yukarıda anılan kişiler/kuruluşlar itibari ile (yurt içinde-dışına) paylaşım, aktarım, aktarılma, transfer, imha (yok edilme, silinme veya anonimleştirme) işlemleri ve kanunlara uygun sair yöntemler ile işlenebilmekte ve aktarılabilmektedir (Bundan böyle hepsini birlikte ifade etmek üzere “işlenme” veya “işlem(e)” diye anılacaktır).
(*)  Akademik Masa’ya bağlı şirketler ile mevcut-müstakbel diğer iştirakleridir.
Ziyaretçilerin Şirketimize Akademik Masa, bayileri ve her türlü anlaşmalı kuruluşlarına ait fiziki ve e-ticaret mağazaları-reyonları ile içinde yer aldıkları yapıları-siteleri ziyaretlerine ve buralardan alışverişlerine dair her türlü kişisel olan-olmayan bilgiler de (konum verileri, incelenen ürünler ve alışveriş konusu ürün-tutar bilgileri dahil) cihazlarında ilgili fonksiyonlar açık ise bluetooth, beacon ve genel-özel kablosuz ağ bağlantılarından uygun teknik yöntemler ile alınabilir, yukarıdaki paragrafta belirtilen çerçevede anılan kuruluşlarca yurt içinde ve dışında işlenebilir, aktarılabilir.
Sitemizde Tanımlama Bilgisi (Çerez vb.) Uygulaması
www.akademikmasa.com Sitemizde muhtelif türde çerezler kullanılmaktadır. Bunlar oturum çerezleri, kalıcı çerezler, zorunlu çerezler, işlevsellik çerezleri, analiz çerezleri, ticari çerezler ve üçüncü parti çerezleri gibi tanımlama bilgileridir.
Çerezler ziyaret edilen internet sitesinin düzgün bir şekilde çalışmasını ve geliştirilmesini, kullanıcı deneyiminin kişiselleştirilmesini ve iyileştirilmesini, siteleri oturum açmadan ziyaret edebilmesini ve/veya tarafına (duruma göre internet tarayıcı ve/veya ilgili mobil uygulama kapalı olsa dahi görebileceği) ticari-sosyal amaçlı bildirimler yollanmasını ve genel olarak site kullanıcıları-ziyaretçilerine gerek ilgili sitede, gerek başkalarına ait sitelerde (sosyal medya-ağlar ve online reklam ağları dahil) genel ya da özelleştirilmiş bilgilendirmeler, reklam ve tanıtımlar sunulmasını-iletilmesini sağlamak amacıyla bilgisayarlara ve mobil cihazlara yerleştirilen küçük veri parçacıklarıdır.
Çerezler bilgisayar-cihazlarda, varsa kanuni azami süre aşılmamak kaydıyla, amaca uygun bir süre ile tutulurlar.
Sitemizi (mobil versiyonları dahil) kullanan Ziyaretçiler yukarıda belirtilen uygulamayı, keza ilgili tanımlama bilgilerinin burada, kişisel veri mevzuatında ve bu bilgilendirme metninin diğer kısımlarında çeşitli bilgileriniz için öngörülen amaçlarla ve kapsamda-şartlarda işlenmesini (bu çerçevede üçüncü kişilere aktarım-paylaşımları ve kullanmaları dahil) kabul etmiş sayılırlar.
Ziyaretçiler istedikleri her zaman cihazlarındaki program ve/veya işletim sistemi ve/veya internet tarayıcısının ayarlarından çerezleri düzenleyerek kaldırabilirler ve/veya anılan bildirimleri durdurabilirler (Bu takdirde Sitemizin/ilgili cihazın/programın arzu edildiği gibi çalışmayabileceği ve/veya bildirim içeriklerinden haberdar olunamayacağı bilinmelidir).
İletişimler
Ziyaretçilerimiz ile, yine kanunlara uygun şekilde, her türlü ürün ve hizmetlere ilişkin tanıtım, reklam, iletişim, promosyon, satış ve pazarlama amacıyla, keza mağaza kartı, kredi kartı ve üyelik/müşteri bilgilendirme, işlem, uygulamaları için Şirketimiz  Akademik Masa, SMS/kısa mesaj, anlık bildirim, otomatik arama, bilgisayar, telefon, e-posta/mail, faks, (cihazınızda açık ise) her türlü bildirimler, bluetooth, beacon-diğer her türlü genel-özel kablosuz ağlar ve diğer elektronik iletişim araçları ile sosyal, ticari ve sair elektronik iletişimler yapılabilir, Ziyaretçilere ticari elektronik iletiler gönderilebilir.
İşlenen – Aktarılan Kişisel Verileriniz ve Kişisel Verilerinize Dair Kanuni Haklarınız
Değerli Ziyaretçimiz, isim, soyisim, rumuz, yaş/doğum tarihi, cinsiyet, medeni durum, evlilik tarihi, çocuk durumu, sahip olunan ulaşım aracı, yaşanılan bölge, adres ve teslimat adresi, eğitim düzeyi, meslek/iş, kültürel, sanatsal, sportif, tatil vs. ilgi alanları-hobiler ve alışkanlıklar gibi demografik üye/kullanıcı/müşteri bilgileri, özel-resmi kimlik, kimlik no. ve vergi bilgileri, fotoğraf, (güvenlik amaçlı) görüntü kayıtları ve çağrı merkezi görüşme ses kayıtları, kıyafet dahil her türlü ürüne ve hizmete ilişkin alışveriş alışkanlığı yapılan bilgilendirme, tanıtım ve reklamlar, keza her türlü öneriler çerçevesinde aldıkları kararlardan, bunlara göre yaptıkları hertürlü işlem ve uygulama ile sonuçlarından Ziyaretçiler sorumludurlar.
Herhangi bir Sitemiz Ziyaretçisinin hukuki/fiili ehliyet durumunu bilemeyeceğimizden, çocukların ve diğer reşit olmayan kişilerin kullanımları, bilgileri ve bunların işlenme-işlemleri hususunda sorumluluk kanuni temsilcilerine ait olup kişisel verilerine (ve duruma göre keza iletişimlere) ilişkin haklarını da kanuni temsilcileri marifetiyle kullanabilirler.
Alışverişler ve Diğer Tüketici İşlemleri
Ziyaretçilerin yukarıda belirtilen suretler ile bilgilenmeleri ve/veya taraflarına yapılan iletişimler, bilgilendirmeler, bildirimler, tanıtım ve reklamlar neticesi bir ürün/hizmet satın alması söz konusu olursa anılan işlem ayrıca ve kanuni usulünce ilgili satıcı/sağlayıcı ile yapacakları tüketici sözleşmesine tabidir. Tüketici sözleşmesi kendi şartlarında ve tarafları arasında uygulanır.
(Varsa) Sitemizden alışverişlerinizde, her işlem sırasında göreceğiniz sipariş ön bilgilendirme formu-mesafeli satış sözleşmesi şartları geçerli olacaktır.
Site İçeriği Üzerinde Haklar
Sitemizdeki her türlü bilgi ve içerik ile bunların düzenlenmesi, revizyonu ve kısmen/tamamen kullanımı konusunda; Şirketimizin anlaşmasına göre diğer üçüncü sahıslara ait olanlar hariç; tüm fikri-sınai haklar ve mülkiyet hakları Şirketimize ve/veya  Akademik Masa’ya aittir.
Tanıtım ve Pazarlama Faaliyetlerine İlişkin İzinler
Kullanıcı, kayıt işlemleri esnasında veya sınav sonrasında kendi rızasıyla beyan ettiği sınav sonucu, başarı sırası, puanı, ad-soyad, profil fotoğrafı ve kuruma ilettiği memnuniyet mesajlarının; Hizmet Sağlayıcı (Kurum) tarafından sosyal medya mecralarında, web sitesinde, dijital reklam ve tanıtım materyallerinde yayınlanmasını kabul ve beyan eder.
İşbu izin hiçbir şekilde mesafeli satış sözleşmesinin ifası veya hizmetin sunulması için bir ön şart değildir. Alıcı, verdiği açık rızayı dilediği zaman [destek/iletişim e-posta adresi] üzerinden bildirimde bulunarak geri alma hakkına sahiptir. Rızanın geri alınması, bu tarihe kadar gerçekleşmiş olan tanıtım ve paylaşımların hukuka uygunluğunu etkilemez.

Değişiklikler
Şirketimiz gizlilik, kişisel veri saklama-kullanım ve imha politikası ve Site kullanım şartları gibi konularda, keza sunacağı ürün, hizmet ve fırsatlarda, kampanya vb.lerinde gerekli görebileceği her türlü değişikliği yapma hakkını saklı tutar; bu değişiklikler Şirketimizce Siteden veya diğer uygun yöntemler ile duyurulduğu andan itibaren geçerli olur.
Tüm bu konularda ek bilgi istemlerinizi, her türlü talep ve şikayetlerinizi aşağıdaki iletişim kanallarından ulaşarak Şirketimiz Akademik Masa’ya bildirebilirsiniz. İlgili talebin yasalar gereği belirli bir prosedürde (usulde-zamanda-şekilde) yapılması gereken hallerde söz konusu prosedüre uyulması gerekir.

`;
